# Generated by Django 5.0.6 on 2024-06-05 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar',
        ),
    ]
