# Generated by Django 5.0.6 on 2024-07-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_searchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
