# Generated by Django 5.0.6 on 2024-07-10 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='app_product_search__0a6668_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
    ]
